build:
  build_starting:
     image: node:argon
     commands:
      - echo "Beginning new build"
  run_tests:
    image: node:argon
    commands:
      - echo "Running tests"

publish:
  docker:
    repo: $$DOCKER_USERNAME/c2k_msg
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    tag: latest

deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: $$MANTL_USERNAME
            password: $$MANTL_PASSWORD
        urls:
            - https://$$MANTL_CONTROL/marathon/v2/apps/imapex/c2k/c2kmsgbroker/restart?force=true
